[Tarea 10] Ejercicios Unidad 04-C | Descomposición LU

Nombre: Alegria Farinango

Fecha: 28/01/2026

Repositorio: 

1. Multiplicación Matriz-Matriz

In [16]:
import numpy as np

# 1a
A1a = np.array([[2, -3], [3, -1]])
B1a = np.array([[1, 5], [2, 0]])
print("1a:\n", A1a @ B1a)

# 1b
A1b = np.array([[2, -3], [3, -1]])
B1b = np.array([[1, 5, -4], [-3, 2, 0]])
print("\n1b:\n", A1b @ B1b)

# 1c
A1c = np.array([[2, -3, 1], [4, 3, 0], [5, 2, -4]])
B1c = np.array([[0, 1, -2], [1, 0, -1], [2, 3, -2]])
print("\n1c:\n", A1c @ B1c)

# 1d
A1d = np.array([[2, 1, 2], [-2, 3, 0], [2, -1, 3]])
B1d = np.array([[1, -2], [-4, 1], [0, 2]])
print("\n1d:\n", A1d @ B1d)

1a:
 [[-4 10]
 [ 1 15]]

1b:
 [[ 11   4  -8]
 [  6  13 -12]]

1c:
 [[ -1   5  -3]
 [  3   4 -11]
 [ -6  -7  -4]]

1d:
 [[ -2   1]
 [-14   7]
 [  6   1]]


2. Matrices No Singulares e Inversas

In [17]:
def procesar_2(M, nombre):
    det = np.linalg.det(M)
    print(f"\n--- Matriz {nombre} ---")
    if not np.isclose(det, 0):
        print("Es NO singular. Inversa:\n", np.linalg.inv(M))
    else:
        print("Es SINGULAR (No tiene inversa).")

procesar_2(np.array([[4, 2, 6], [3, 0, 7], [-2, -1, -3]]), "2a")
procesar_2(np.array([[1, 2, 0], [2, 1, -1], [3, 1, 1]]), "2b")
procesar_2(np.array([[1, 1, -1, 1], [1, 2, -4, -2], [2, 1, 1, 5], [-1, 0, -2, -4]]), "2c")
procesar_2(np.array([[4, 0, 0, 0], [6, 7, 0, 0], [9, 11, 1, 0], [5, 4, 1, 1]]), "2d")


--- Matriz 2a ---
Es SINGULAR (No tiene inversa).

--- Matriz 2b ---
Es NO singular. Inversa:
 [[-0.25   0.25   0.25 ]
 [ 0.625 -0.125 -0.125]
 [ 0.125 -0.625  0.375]]

--- Matriz 2c ---
Es SINGULAR (No tiene inversa).

--- Matriz 2d ---
Es NO singular. Inversa:
 [[ 0.25        0.          0.          0.        ]
 [-0.21428571  0.14285714 -0.         -0.        ]
 [ 0.10714286 -1.57142857  1.         -0.        ]
 [-0.5         1.         -1.          1.        ]]


3. Sistemas con misma Matriz de Coeficientes

In [18]:
A3 = np.array([[1, -1, 2, -1], [1, 0, -1, 1], [2, 1, 3, -4], [0, -1, 1, -1]])
b3_1 = np.array([6, 4, -2, 5])
b3_2 = np.array([1, 1, 2, -1])

print("Solución Sistema 3.1:", np.linalg.solve(A3, b3_1))
print("Solución Sistema 3.2:", np.linalg.solve(A3, b3_2))

Solución Sistema 3.1: [ 3. -6. -2. -1.]
Solución Sistema 3.2: [1. 1. 1. 1.]


4. Valor de $\alpha$ para Matriz Singular

In [19]:
import sympy as sp
a_sym = sp.symbols('alpha')
A4 = sp.Matrix([[1, -1, a_sym], [2, 2, 1], [0, a_sym, -1.5]])
sol_alpha = sp.solve(A4.det(), a_sym)
print("Valores de alpha para que A sea singular:", sol_alpha)

Valores de alpha para que A sea singular: [-1.50000000000000, 2.00000000000000]


5. Resolución de Sistemas $LUx = b$

In [20]:
def resolver_lu_manual(L, U, b):
    y = np.linalg.solve(L, b)
    x = np.linalg.solve(U, y)
    return x

# 5a
L5a, U5a = np.array([[1,0,0],[2,1,0],[-1,0,1]]), np.array([[2,3,-1],[0,-2,1],[0,0,3]])
b5a = np.array([2, -1, 1])
print("Solución 5a:", resolver_lu_manual(L5a, U5a, b5a))

# 5b
L5b, U5b = np.array([[2,0,0],[-1,1,0],[3,2,-1]]), np.array([[1,1,1],[0,1,2],[0,0,1]])
b5b = np.array([-1, 3, 0])
print("Solución 5b:", resolver_lu_manual(L5b, U5b, b5b))

Solución 5a: [-3.  3.  1.]
Solución 5b: [ 0.5 -4.5  3.5]


6. Factorización LU

In [21]:
from scipy.linalg import lu

def mostrar_lu(A, nombre):
    P, L, U = lu(A)
    print(f"\n--- Factorización LU {nombre} ---")
    print("L:\n", L, "\nU:\n", U)

# Matrices de los ejercicios
mostrar_lu(np.array([[2, -1, 1], [3, 3, 9], [3, 3, 5]]), "6a")
mostrar_lu(np.array([[1.012, -2.132, 3.104], [-2.132, 4.096, -7.013], [3.104, -7.013, 0.014]]), "6b")
mostrar_lu(np.array([[2,0,0,0],[1,1.5,0,0],[0,-3,0.5,0],[2,-2,1,1]]), "6c")
mostrar_lu(np.array([[2.1756, 4.0231, -2.1732, 5.1967], [-4.0231, 6.0000, 0, 1.1973], 
                     [-1.0000, -5.2107, 1.1111, 0], [6.0235, 7.0000, 0, -4.1561]]), "6d")


--- Factorización LU 6a ---
L:
 [[ 1.          0.          0.        ]
 [ 0.66666667  1.          0.        ]
 [ 1.         -0.          1.        ]] 
U:
 [[ 3.  3.  9.]
 [ 0. -3. -5.]
 [ 0.  0. -4.]]

--- Factorización LU 6b ---
L:
 [[ 1.          0.          0.        ]
 [-0.68685567  1.          0.        ]
 [ 0.32603093 -0.21424728  1.        ]] 
U:
 [[ 3.104      -7.013       0.014     ]
 [ 0.         -0.72091881 -7.00338402]
 [ 0.          0.          1.59897957]]

--- Factorización LU 6c ---
L:
 [[ 1.          0.          0.          0.        ]
 [ 0.          1.          0.          0.        ]
 [ 1.          0.66666667  1.          0.        ]
 [ 0.5        -0.5         0.375       1.        ]] 
U:
 [[ 2.          0.          0.          0.        ]
 [ 0.         -3.          0.5         0.        ]
 [ 0.          0.          0.66666667  1.        ]
 [ 0.          0.          0.         -0.375     ]]

--- Factorización LU 6d ---
L:
 [[ 1.          0.          0.          0.  

7. Resolución de Sistemas usando LU

In [22]:
def resolver_punto_7(A, b, nombre):
    P, L, U = lu(A)
    y = np.linalg.solve(L, P.T @ b)
    x = np.linalg.solve(U, y)
    print(f"Resultado {nombre}:", x)

# 7a
resolver_punto_7(np.array([[2,-1,1],[3,3,9],[3,3,5]]), np.array([-1,0,4]), "7a")
# 7b
resolver_punto_7(np.array([[1.012, -2.132, 3.104], [-2.132, 4.096, -7.013], [3.104, -7.013, 0.014]]), 
                 np.array([1.984, -5.049, -3.895]), "7b")
# 7c
resolver_punto_7(np.array([[2,0,0,0],[1,1.5,0,0],[0,-3,0.5,0],[2,-2,1,1]]), 
                 np.array([3, 4.5, -6.6, 0.8]), "7c")
# 7d
resolver_punto_7(np.array([[2.1756, 4.0231, -2.1732, 5.1967], [-4.0231, 6.0000, 0, 1.1973], 
                           [-1.0000, -5.2107, 1.1111, 0], [6.0235, 7.0000, 0, -4.1561]]), 
                 np.array([17.102, -6.1593, 3.0004, 0.0000]), "7d")

Resultado 7a: [ 1.  2. -1.]
Resultado 7b: [1. 1. 1.]
Resultado 7c: [ 1.5  2.  -1.2  3. ]
Resultado 7d: [2.9398512  0.0706777  5.67773512 4.37981223]
